export type SurahMeta = {
  number: number;
  name: string;
  nameEn: string;
  startPage: number;
};

// Standard Medina Mushaf (alquran.cloud) — 114 surahs
export const SURAHS: SurahMeta[] = [
  { number: 1,   name: "الفاتحة",   nameEn: "Al-Fatiha",     startPage: 1   },
  { number: 2,   name: "البقرة",    nameEn: "Al-Baqarah",    startPage: 2   },
  { number: 3,   name: "آل عمران",  nameEn: "Al-Imran",      startPage: 50  },
  { number: 4,   name: "النساء",    nameEn: "An-Nisa",       startPage: 77  },
  { number: 5,   name: "المائدة",   nameEn: "Al-Ma'idah",    startPage: 106 },
  { number: 6,   name: "الأنعام",   nameEn: "Al-An'am",      startPage: 128 },
  { number: 7,   name: "الأعراف",   nameEn: "Al-A'raf",      startPage: 151 },
  { number: 8,   name: "الأنفال",   nameEn: "Al-Anfal",      startPage: 177 },
  { number: 9,   name: "التوبة",    nameEn: "At-Tawbah",     startPage: 187 },
  { number: 10,  name: "يونس",      nameEn: "Yunus",         startPage: 208 },
  { number: 11,  name: "هود",       nameEn: "Hud",           startPage: 221 },
  { number: 12,  name: "يوسف",      nameEn: "Yusuf",         startPage: 235 },
  { number: 13,  name: "الرعد",     nameEn: "Ar-Ra'd",       startPage: 249 },
  { number: 14,  name: "إبراهيم",   nameEn: "Ibrahim",       startPage: 255 },
  { number: 15,  name: "الحجر",     nameEn: "Al-Hijr",       startPage: 262 },
  { number: 16,  name: "النحل",     nameEn: "An-Nahl",       startPage: 267 },
  { number: 17,  name: "الإسراء",   nameEn: "Al-Isra",       startPage: 282 },
  { number: 18,  name: "الكهف",     nameEn: "Al-Kahf",       startPage: 293 },
  { number: 19,  name: "مريم",      nameEn: "Maryam",        startPage: 305 },
  { number: 20,  name: "طه",        nameEn: "Ta-Ha",         startPage: 312 },
  { number: 21,  name: "الأنبياء",  nameEn: "Al-Anbiya",     startPage: 322 },
  { number: 22,  name: "الحج",      nameEn: "Al-Hajj",       startPage: 332 },
  { number: 23,  name: "المؤمنون",  nameEn: "Al-Mu'minun",   startPage: 342 },
  { number: 24,  name: "النور",     nameEn: "An-Nur",        startPage: 350 },
  { number: 25,  name: "الفرقان",   nameEn: "Al-Furqan",     startPage: 359 },
  { number: 26,  name: "الشعراء",   nameEn: "Ash-Shu'ara",   startPage: 367 },
  { number: 27,  name: "النمل",     nameEn: "An-Naml",       startPage: 377 },
  { number: 28,  name: "القصص",     nameEn: "Al-Qasas",      startPage: 385 },
  { number: 29,  name: "العنكبوت",  nameEn: "Al-Ankabut",    startPage: 396 },
  { number: 30,  name: "الروم",     nameEn: "Ar-Rum",        startPage: 404 },
  { number: 31,  name: "لقمان",     nameEn: "Luqman",        startPage: 411 },
  { number: 32,  name: "السجدة",    nameEn: "As-Sajdah",     startPage: 415 },
  { number: 33,  name: "الأحزاب",   nameEn: "Al-Ahzab",      startPage: 418 },
  { number: 34,  name: "سبأ",       nameEn: "Saba",          startPage: 428 },
  { number: 35,  name: "فاطر",      nameEn: "Fatir",         startPage: 434 },
  { number: 36,  name: "يس",        nameEn: "Ya-Sin",        startPage: 440 },
  { number: 37,  name: "الصافات",   nameEn: "As-Saffat",     startPage: 446 },
  { number: 38,  name: "ص",         nameEn: "Sad",           startPage: 453 },
  { number: 39,  name: "الزمر",     nameEn: "Az-Zumar",      startPage: 458 },
  { number: 40,  name: "غافر",      nameEn: "Ghafir",        startPage: 467 },
  { number: 41,  name: "فصلت",      nameEn: "Fussilat",      startPage: 477 },
  { number: 42,  name: "الشورى",    nameEn: "Ash-Shura",     startPage: 483 },
  { number: 43,  name: "الزخرف",    nameEn: "Az-Zukhruf",    startPage: 489 },
  { number: 44,  name: "الدخان",    nameEn: "Ad-Dukhan",     startPage: 496 },
  { number: 45,  name: "الجاثية",   nameEn: "Al-Jathiyah",   startPage: 499 },
  { number: 46,  name: "الأحقاف",   nameEn: "Al-Ahqaf",      startPage: 502 },
  { number: 47,  name: "محمد",      nameEn: "Muhammad",      startPage: 507 },
  { number: 48,  name: "الفتح",     nameEn: "Al-Fath",       startPage: 511 },
  { number: 49,  name: "الحجرات",   nameEn: "Al-Hujurat",    startPage: 515 },
  { number: 50,  name: "ق",         nameEn: "Qaf",           startPage: 518 },
  { number: 51,  name: "الذاريات",  nameEn: "Adh-Dhariyat",  startPage: 520 },
  { number: 52,  name: "الطور",     nameEn: "At-Tur",        startPage: 523 },
  { number: 53,  name: "النجم",     nameEn: "An-Najm",       startPage: 526 },
  { number: 54,  name: "القمر",     nameEn: "Al-Qamar",      startPage: 528 },
  { number: 55,  name: "الرحمن",    nameEn: "Ar-Rahman",     startPage: 531 },
  { number: 56,  name: "الواقعة",   nameEn: "Al-Waqi'ah",    startPage: 534 },
  { number: 57,  name: "الحديد",    nameEn: "Al-Hadid",      startPage: 537 },
  { number: 58,  name: "المجادلة",  nameEn: "Al-Mujadila",   startPage: 542 },
  { number: 59,  name: "الحشر",     nameEn: "Al-Hashr",      startPage: 545 },
  { number: 60,  name: "الممتحنة",  nameEn: "Al-Mumtahanah", startPage: 549 },
  { number: 61,  name: "الصف",      nameEn: "As-Saf",        startPage: 551 },
  { number: 62,  name: "الجمعة",    nameEn: "Al-Jumu'ah",    startPage: 553 },
  { number: 63,  name: "المنافقون", nameEn: "Al-Munafiqun",  startPage: 554 },
  { number: 64,  name: "التغابن",   nameEn: "At-Taghabun",   startPage: 556 },
  { number: 65,  name: "الطلاق",    nameEn: "At-Talaq",      startPage: 558 },
  { number: 66,  name: "التحريم",   nameEn: "At-Tahrim",     startPage: 560 },
  { number: 67,  name: "الملك",     nameEn: "Al-Mulk",       startPage: 562 },
  { number: 68,  name: "القلم",     nameEn: "Al-Qalam",      startPage: 564 },
  { number: 69,  name: "الحاقة",    nameEn: "Al-Haqqah",     startPage: 566 },
  { number: 70,  name: "المعارج",   nameEn: "Al-Ma'arij",    startPage: 568 },
  { number: 71,  name: "نوح",       nameEn: "Nuh",           startPage: 570 },
  { number: 72,  name: "الجن",      nameEn: "Al-Jinn",       startPage: 572 },
  { number: 73,  name: "المزمل",    nameEn: "Al-Muzzammil",  startPage: 574 },
  { number: 74,  name: "المدثر",    nameEn: "Al-Muddaththir",startPage: 575 },
  { number: 75,  name: "القيامة",   nameEn: "Al-Qiyamah",    startPage: 577 },
  { number: 76,  name: "الإنسان",   nameEn: "Al-Insan",      startPage: 578 },
  { number: 77,  name: "المرسلات",  nameEn: "Al-Mursalat",   startPage: 580 },
  { number: 78,  name: "النبأ",     nameEn: "An-Naba",       startPage: 582 },
  { number: 79,  name: "النازعات",  nameEn: "An-Nazi'at",    startPage: 583 },
  { number: 80,  name: "عبس",       nameEn: "Abasa",         startPage: 585 },
  { number: 81,  name: "التكوير",   nameEn: "At-Takwir",     startPage: 586 },
  { number: 82,  name: "الانفطار",  nameEn: "Al-Infitar",    startPage: 587 },
  { number: 83,  name: "المطففين",  nameEn: "Al-Mutaffifin", startPage: 587 },
  { number: 84,  name: "الانشقاق",  nameEn: "Al-Inshiqaq",   startPage: 589 },
  { number: 85,  name: "البروج",    nameEn: "Al-Buruj",      startPage: 590 },
  { number: 86,  name: "الطارق",    nameEn: "At-Tariq",      startPage: 591 },
  { number: 87,  name: "الأعلى",    nameEn: "Al-A'la",       startPage: 591 },
  { number: 88,  name: "الغاشية",   nameEn: "Al-Ghashiyah",  startPage: 592 },
  { number: 89,  name: "الفجر",     nameEn: "Al-Fajr",       startPage: 593 },
  { number: 90,  name: "البلد",     nameEn: "Al-Balad",      startPage: 594 },
  { number: 91,  name: "الشمس",     nameEn: "Ash-Shams",     startPage: 595 },
  { number: 92,  name: "الليل",     nameEn: "Al-Layl",       startPage: 595 },
  { number: 93,  name: "الضحى",     nameEn: "Ad-Duha",       startPage: 596 },
  { number: 94,  name: "الشرح",     nameEn: "Ash-Sharh",     startPage: 596 },
  { number: 95,  name: "التين",     nameEn: "At-Tin",        startPage: 597 },
  { number: 96,  name: "العلق",     nameEn: "Al-Alaq",       startPage: 597 },
  { number: 97,  name: "القدر",     nameEn: "Al-Qadr",       startPage: 598 },
  { number: 98,  name: "البينة",    nameEn: "Al-Bayyinah",   startPage: 598 },
  { number: 99,  name: "الزلزلة",   nameEn: "Az-Zalzalah",   startPage: 599 },
  { number: 100, name: "العاديات",  nameEn: "Al-Adiyat",     startPage: 599 },
  { number: 101, name: "القارعة",   nameEn: "Al-Qari'ah",    startPage: 600 },
  { number: 102, name: "التكاثر",   nameEn: "At-Takathur",   startPage: 600 },
  { number: 103, name: "العصر",     nameEn: "Al-Asr",        startPage: 601 },
  { number: 104, name: "الهمزة",    nameEn: "Al-Humazah",    startPage: 601 },
  { number: 105, name: "الفيل",     nameEn: "Al-Fil",        startPage: 601 },
  { number: 106, name: "قريش",      nameEn: "Quraysh",       startPage: 602 },
  { number: 107, name: "الماعون",   nameEn: "Al-Ma'un",      startPage: 602 },
  { number: 108, name: "الكوثر",    nameEn: "Al-Kawthar",    startPage: 602 },
  { number: 109, name: "الكافرون",  nameEn: "Al-Kafirun",    startPage: 603 },
  { number: 110, name: "النصر",     nameEn: "An-Nasr",       startPage: 603 },
  { number: 111, name: "المسد",     nameEn: "Al-Masad",      startPage: 603 },
  { number: 112, name: "الإخلاص",   nameEn: "Al-Ikhlas",     startPage: 604 },
  { number: 113, name: "الفلق",     nameEn: "Al-Falaq",      startPage: 604 },
  { number: 114, name: "الناس",     nameEn: "An-Nas",        startPage: 604 },
];

export function getSurahForPage(page: number): SurahMeta {
  let result = SURAHS[0];
  for (const s of SURAHS) {
    if (s.startPage <= page) result = s;
    else break;
  }
  return result;
}

export function getJuzForPage(page: number): number {
  return Math.min(30, Math.max(1, Math.ceil((page / 604) * 30)));
}
